-- Table: CATEGORY
CREATE TABLE CATEGORY (
    C_ID INT AUTO_INCREMENT PRIMARY KEY,
    C_NAME VARCHAR(255) NOT NULL
);

-- Inserting values into CATEGORY
INSERT INTO CATEGORY (C_NAME) VALUES 
('Sandwich'), 
('Fast Food'), 
('Beverages'), 
('Burger'), 
('Desserts'), 
('Breakfast');

-- View for CATEGORY
CREATE VIEW CATEGORY1 AS 
SELECT C_ID, C_NAME FROM CATEGORY;

-- Table: PRODUCT
CREATE TABLE PRODUCT (
    P_ID INT AUTO_INCREMENT PRIMARY KEY,
    P_NAME VARCHAR(255) NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    C_ID INT,
    FOREIGN KEY (C_ID) REFERENCES CATEGORY(C_ID) ON DELETE CASCADE
);

-- Inserting values into PRODUCT
INSERT INTO PRODUCT (P_NAME, PRICE, C_ID) VALUES
('McChicken Burger', 125.00, 4),
('McChicken Nuggets', 250.00, 1),
('Filet-O-Fish Burger', 250.00, 1),
('Mc Arabia Burger', 200.00, 4),
('Double McChicken Burger', 100.00, 4),
('Spicy Chicken Burger', 190.00, 1),
('Beef Burger', 120.00, 4),
('McFlurry', 350.00, 5),
('Hot Chocolate', 400.00, 5),
('Tea', 160.00, 6);

-- View for PRODUCT
CREATE VIEW PRODUCT1 AS 
SELECT P_ID, P_NAME, PRICE, C_ID FROM PRODUCT;

-- Table: CUSTOMER
CREATE TABLE CUSTOMER (
    CUST_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUST_NAME VARCHAR(255) NOT NULL,
    CONTACT VARCHAR(20) NOT NULL
);

-- Inserting values into CUSTOMER
INSERT INTO CUSTOMER (CUST_NAME, CONTACT) VALUES
('Ali Khan', '03214567890'),
('Sarah Ahmed', '03001234567'),
('John Doe', '03459876543');

-- View for CUSTOMER
CREATE VIEW CUSTOMER1 AS 
SELECT CUST_ID, CUST_NAME, CONTACT FROM CUSTOMER;

-- Table: SALE
CREATE TABLE SALE (
    S_ID INT AUTO_INCREMENT PRIMARY KEY,
    D_O_S DATE NOT NULL,
    QUANTITY INT NOT NULL,
    PRICEE DECIMAL(10,2) NOT NULL,
    GST VARCHAR(10) NOT NULL,
    CUST_ID INT,
    C_ID INT,
    P_ID INT,
    FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID) ON DELETE CASCADE,
    FOREIGN KEY (C_ID) REFERENCES CATEGORY(C_ID) ON DELETE CASCADE,
    FOREIGN KEY (P_ID) REFERENCES PRODUCT(P_ID) ON DELETE CASCADE
);

-- Inserting values into SALE
INSERT INTO SALE (D_O_S, QUANTITY, PRICEE, GST, CUST_ID, C_ID, P_ID) VALUES
('2019-12-20', 1, 125.00, '5%', 1, 4, 1),
('2019-12-21', 2, 250.00, '5%', 2, 1, 2),
('2019-12-22', 1, 150.00, '5%', 3, 1, 3),
('2019-12-23', 1, 200.00, '5%', 1, 4, 4),
('2019-12-24', 2, 100.00, '5%', 2, 4, 5),
('2019-12-25', 3, 190.00, '5%', 3, 1, 6),
('2019-12-26', 5, 120.00, '5%', 1, 4, 7),
('2019-12-27', 2, 350.00, '5%', 2, 5, 8),
('2019-12-28', 3, 400.00, '5%', 3, 5, 9),
('2019-12-29', 1, 160.00, '5%', 1, 6, 10);

-- View for SALE
CREATE VIEW SALE1 AS 
SELECT S_ID, D_O_S, QUANTITY, PRICEE, GST, CUST_ID, C_ID, P_ID FROM SALE;

-- Table: EMPLOYEE
CREATE TABLE EMPLOYEE (
    E_ID INT AUTO_INCREMENT PRIMARY KEY,
    E_NAME VARCHAR(255) NOT NULL,
    ROLE VARCHAR(255) NOT NULL,
    SALARY DECIMAL(10,2) NOT NULL
);

-- Inserting values into EMPLOYEE
INSERT INTO EMPLOYEE (E_NAME, ROLE, SALARY) VALUES
('Ahmad Raza', 'Manager', 50000),
('Hina Khan', 'Cashier', 25000),
('Bilal Ahmed', 'Chef', 35000);

-- View for EMPLOYEE
CREATE VIEW EMPLOYEE1 AS 
SELECT E_ID, E_NAME, ROLE, SALARY FROM EMPLOYEE;

-- Table: ORDERS
CREATE TABLE ORDERS (
    O_ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_DATE DATE NOT NULL,
    CUST_ID INT,
    E_ID INT,
    FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID) ON DELETE CASCADE,
    FOREIGN KEY (E_ID) REFERENCES EMPLOYEE(E_ID) ON DELETE CASCADE
);

-- Inserting values into ORDERS
INSERT INTO ORDERS (ORDER_DATE, CUST_ID, E_ID) VALUES
('2019-12-20', 1, 2),
('2019-12-21', 2, 3),
('2019-12-22', 3, 1),
('2019-12-23', 1, 2),
('2019-12-24', 2, 3);

-- View for ORDERS
CREATE VIEW ORDERS1 AS 
SELECT O_ID, ORDER_DATE, CUST_ID, E_ID FROM ORDERS;
